### PR TITLE
refactor: remove guppy3 unnecessary dependency

### LINKED ISSUE #19: Eliminate dependencies
**Is your feature request related to a problem? Please describe.**
I was looking at the dependencies of it seems that we could eliminate some of them. More specifically do we really need the `guppy` package?

https://github.com/zavolanlab/tin-score-calculation/blob/3aeb38415aaa1e726cdbc8731e4c2587ef966d99/scripts/calculate-tin.py#L28

**Describe the solution you'd like**
The maintenance of the package will be easier if we will not use the specific package. 

@mzavolan @meric466 @AngryMaciek Do you think it can be eliminated?

### PR DESCRIPTION
**Pull request by AngryMaciek**
## Description

Remove old unnecessary dependency for tin score calculation: `guppy3`, it was not used anywhere in the code actually.

Fixes #19 

## Type of change

- [x] Refactoring

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by AngryMaciek** [comment]
No, unfortunately, this does not fix #18...

**Comment by fgypas** [comment]
> No, unfortunately, this does not fix #18...

OK, at least we know it is not related to `guppy`

**Comment by AngryMaciek** [comment]
OK, IMO it's done; @fgypas please take a look and review(?)

**Review by fgypas — APPROVED** [review]
Looks good to me.

**Pull request merged**
